### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by JustiFox** [smartm13/sayatflood#1]
The script does not work even on your site https://sayatflood.appspot.com

**Comment by smartm13** [comment]
Thanks for bringing this to notice. I've updated the spamming logic and all the corresponding code here.
Still, I'll need more time to deploy changes to the published site.

In case you are interested in just spamming with simple pythonic code:
Just use this function: [try2](https://github.com/smartm13/sayatflood/blob/master/main.py#L224)
```
def try2(URL,MSG,k=1):
    import requests,json
    UNM=URL.split("/")[-1]
    cooked=requests.get('https://sayat.me/'+UNM, headers={'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'}).cookies.get_dict()
    qid=requests.get('https://sayat.me/api/v1/questions/{}?limit=1'.format(UNM), headers={'accept': 'application/vnd.react+json'},cookies=cooked).json()
    if 'result' not in qid:return False
    qid=qid['result'][0]
    for i in range(int(k)):
        mainR = requests.post('https://sayat.me/api/v1/answers/question/{}/{}'.format(UNM,qid), headers={'content-type': 'application/json','accept': 'application/vnd.react+json'}, data=json.dumps({"text":MSG,"override":None,"anonymous":True}),cookies=cooked)
        if 'result' not in mainR.json():break
    return 'result' in mainR.json()
```

Sample Usage to spam some test13 user:
`try2("https://sayat.me/test13", "You have been SPAMMED!!")`

**Comment by JustiFox** [comment]
When I run main.py nothing's happening. Or am I doing something wrong? Running on Amazon AWS. Python 2.7 or 3.5.

Could you give me a little more detail on the launch?

**Comment by smartm13** [comment]
Thanks for pointing out.
Fixed it for local running, as well as updated the readme.

PS: I tried to keep it compatible with all python versions.

**Comment by JustiFox** [comment]
AppEnginePlatformError: URLFetch is not available in this environment.
Debugger PIN: 283-676-515

**Comment by smartm13** [comment]
It seems that this was an error from appengine environment (source:requests_toolbelt).
It was imported for google cloud implementations.
You dont need to install anything apart from Flask and requests.
If you pip installed request_toolbelts then uninstall those libraries first.
Or just comment lines 2,3,4,5 in main.py

**Comment by JustiFox** [comment]
How to make when writing the Russian messages they do not become the characters?

**Comment by smartm13** [comment]
Fixed for both python 2 and 3 versions.

**Comment by JustiFox** [comment]
Can you do the job through a proxy or a TOR network? Because Sayat blocks ip for suspicious activity :(

**Comment by smartm13** [comment]
Yes, we must send spamming requests via proxies to avoid such blocking.  
Either you can setup whole proxy env(tor+stem), after a bunch of spamming requests you renew IP. [refer](https://stackoverflow.com/a/33875657)  
Or you can setup rotating proxies [public proxy servers/premium paid proxy listing]. [refer](https://www.scrapehero.com/how-to-rotate-proxies-and-ip-addresses-using-python-3/) or [this one](https://github.com/constverum/ProxyBroker)

It will take some time for me to fulfill this feature request. For now, I am thinking to at least provide a wrapper around HTTP calls so that you can implement proxy inside that wrapper.

Rather, I suggest you to use google cloud app-engine to deploy your own version of sayatflood.
Over there, they have a pool of IPs, and each time your http-request is sent through a random google ip.

How to deploy on google-app-engine you ask:
Logon to [Google Console](https://console.cloud.google.com)
Create a new project if you dont have one already.
And follow the tutorial to create a new python hello world flask project  
 ( [refer-url](https://console.cloud.google.com/appengine/start?project=<projectID>&serviceId=default&walkthrough_tutorial_id=python_gae_quickstart) replace-projectID-inside-Url )   
Atlast, Replace our main.py instead of that main.py of hello world, then deploy.

**Comment by JustiFox** [comment]
Can you tell me how to fix this?
`Traceback (most recent call last):
  File "main.py", line 248, in <module>
    app.run(host='0.0.0.0', port=8000,threaded=True,debug=True)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error`
